version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
#    restart: always
    hostname: 'gitlab.cnpinfra.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url = 'http://gitlab.cnpinfra.com'
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "ijinc123!"
        gitlab_rails['db_host'] = "172.17.128.100"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
    ports:
      - "80:80"
      - "1922:22"
      - "443:443"

    volumes:
    - "./data:/var/opt/gitlab"
    - "./config:/etc/gitlab"
    - "./log:/var/log/gitlab"
~                                